services:
  - type: web
    name: fastapi
    runtime: docker
    plan: free
    repo: https://github.com/FizzBuzz00/fastapi-boilerplate.git
    region: frankfurt
    branch: main
    envVars:
      - key: MONGO_URL
      - key: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
    buildFilter:
      paths:
      - app/**
  